import type { Product, Collection } from "./types";

/* =========================================================================
   Mock catalogue — NOCTRA.
   Replace this file's data by wiring the Storefront API in ./index.ts;
   no component imports from here directly.
   ========================================================================= */

const CUR = "PLN";

function variant(
  id: string,
  title: string,
  price: number,
  options: Record<string, string>,
  compareAtPrice?: number,
  available = true,
): Product["variants"][number] {
  return { id, title, price, compareAtPrice, available, options, sku: id.toUpperCase() };
}

export const products: Product[] = [
  {
    id: "p-vanta-cob-1200",
    handle: "vanta-cob-1200",
    title: "VANTA COB-1200",
    subtitle: "Obrotowa lampa warsztatowa",
    vendor: "NOCTRA",
    description:
      "Magnetyczna lampa COB 1200 lumenów z obrotową głowicą 180° i korpusem 360°. Przyklej do maski, zawieś na hak, oświetl każdy zakamarek silnika.",
    features: [
      "Główne źródło COB 1200 lm + boczna latarka 200 lm",
      "Obrót głowicy 180° i obrót korpusu 360°",
      "Wbudowane magnesy neodymowe + składany hak",
      "Ładowanie USB-C, do 8 h pracy na jednym ładowaniu",
      "Aluminiowy korpus, klasa odporności IP65",
    ],
    specs: [
      { label: "Strumień świetlny", value: "1200 lm (COB) / 200 lm (spot)" },
      { label: "Akumulator", value: "Li-ion 4000 mAh" },
      { label: "Czas pracy", value: "do 8 h" },
      { label: "Ładowanie", value: "USB-C, 2.5 h" },
      { label: "Odporność", value: "IP65, aluminium" },
      { label: "Mocowanie", value: "Magnes + hak 360°" },
    ],
    price: 149,
    compareAtPrice: 219,
    currencyCode: CUR,
    rating: 4.9,
    reviewCount: 1284,
    images: [],
    options: [
      { name: "Kolor", values: ["Molten Red", "Stealth Black"] },
      { name: "Moc", values: ["1200 lm", "1600 lm"] },
    ],
    variants: [
      variant("v-vanta-red-1200", "Molten Red / 1200 lm", 149, { Kolor: "Molten Red", Moc: "1200 lm" }, 219),
      variant("v-vanta-red-1600", "Molten Red / 1600 lm", 179, { Kolor: "Molten Red", Moc: "1600 lm" }, 249),
      variant("v-vanta-black-1200", "Stealth Black / 1200 lm", 149, { Kolor: "Stealth Black", Moc: "1200 lm" }, 219),
      variant("v-vanta-black-1600", "Stealth Black / 1600 lm", 179, { Kolor: "Stealth Black", Moc: "1600 lm" }, 249),
    ],
    collections: ["oswietlenie", "lampy-cob", "latarki-magnetyczne", "bestsellery"],
    badges: ["bestseller"],
    tags: ["lampa", "cob", "magnetyczna", "warsztat"],
    faq: [
      { q: "Czy magnes utrzyma lampę na masce?", a: "Tak — dwa magnesy neodymowe utrzymują lampę na pionowej masce i pod podwoziem. Hak daje dodatkowy punkt zaczepienia." },
      { q: "Jak długo działa na jednym ładowaniu?", a: "Do 8 h w trybie ekonomicznym (300 lm) i ok. 2,5 h na pełnej mocy 1200 lm." },
      { q: "Czy mogę ładować ją w aucie?", a: "Tak, przez dowolną ładowarkę USB-C 5V/2A — pełne ładowanie zajmuje ok. 2,5 h." },
    ],
    relatedHandles: ["puck-mini", "halo-inspect", "probe-5-5"],
    accent: "molten",
    icon: "flashlight",
  },
  {
    id: "p-probe-5-5",
    handle: "probe-5-5",
    title: "PROBE 5.5",
    subtitle: "Endoskop inspekcyjny USB-C",
    vendor: "NOCTRA",
    description:
      "Wodoodporny endoskop 5,5 mm z 6 diodami LED i kablem 5 m. Podłącz do telefonu (USB-C) lub komputera i zajrzyj tam, gdzie nie sięga wzrok.",
    features: [
      "Sonda 5,5 mm z 6 regulowanymi diodami LED",
      "Kamera 1080p, kąt widzenia 70°",
      "Półsztywny kabel 5 m utrzymujący kształt",
      "Wodoodporność sondy IP67",
      "Plug & play: USB-C (Android / PC) — zero aplikacji premium",
    ],
    specs: [
      { label: "Średnica sondy", value: "5,5 mm" },
      { label: "Rozdzielczość", value: "1080p" },
      { label: "Długość kabla", value: "5 m (półsztywny)" },
      { label: "Oświetlenie", value: "6 × LED, regulacja" },
      { label: "Złącze", value: "USB-C + adapter USB-A" },
      { label: "Odporność sondy", value: "IP67" },
    ],
    price: 119,
    compareAtPrice: 169,
    currencyCode: CUR,
    rating: 4.8,
    reviewCount: 932,
    images: [],
    options: [
      { name: "Średnica", values: ["5,5 mm", "7,0 mm"] },
      { name: "Długość", values: ["2 m", "5 m", "10 m"] },
    ],
    variants: [
      variant("v-probe-55-2", "5,5 mm / 2 m", 99, { "Średnica": "5,5 mm", "Długość": "2 m" }, 149),
      variant("v-probe-55-5", "5,5 mm / 5 m", 119, { "Średnica": "5,5 mm", "Długość": "5 m" }, 169),
      variant("v-probe-70-5", "7,0 mm / 5 m", 129, { "Średnica": "7,0 mm", "Długość": "5 m" }, 179),
      variant("v-probe-70-10", "7,0 mm / 10 m", 159, { "Średnica": "7,0 mm", "Długość": "10 m" }, 209),
    ],
    collections: ["inspekcja", "endoskopy-usb-c", "kamery-inspekcyjne", "bestsellery"],
    badges: ["bestseller"],
    tags: ["endoskop", "kamera", "inspekcja", "usb-c"],
    faq: [
      { q: "Czy zadziała z iPhone'em?", a: "Modele z USB-C (iPhone 15+) — tak, bezpośrednio. Starsze z Lightning wymagają adaptera OTG." },
      { q: "Czy potrzebuję płatnej aplikacji?", a: "Nie. Działa z darmowymi aplikacjami kamery UVC oraz bezpośrednio na PC (Windows/Mac)." },
      { q: "Czy sondę można zanurzyć?", a: "Sonda i kabel mają klasę IP67 — krótkie zanurzenie nie szkodzi. Złącze trzymaj suche." },
    ],
    relatedHandles: ["probe-dual", "therma-scan", "vanta-cob-1200"],
    accent: "volt",
    icon: "camera",
  },
  {
    id: "p-puck-mini",
    handle: "puck-mini",
    title: "PUCK MINI",
    subtitle: "Magnetyczna latarka EDC",
    vendor: "NOCTRA",
    description:
      "Kieszonkowa latarka 500 lm z magnetyczną podstawą i klipsem. Mieści się w dłoni, trzyma się każdej stalowej powierzchni.",
    features: [
      "500 lm w obudowie wielkości breloka",
      "Magnetyczna podstawa + obrotowy klips",
      "Ładowanie USB-C, wskaźnik naładowania",
      "Tryb światła ciągłego i strobo SOS",
    ],
    specs: [
      { label: "Strumień", value: "500 lm" },
      { label: "Akumulator", value: "1200 mAh" },
      { label: "Czas pracy", value: "do 6 h" },
      { label: "Waga", value: "62 g" },
      { label: "Odporność", value: "IP54" },
    ],
    price: 69,
    currencyCode: CUR,
    rating: 4.7,
    reviewCount: 421,
    images: [],
    options: [{ name: "Kolor", values: ["Stealth Black", "Molten Red"] }],
    variants: [
      variant("v-puck-black", "Stealth Black", 69, { Kolor: "Stealth Black" }),
      variant("v-puck-red", "Molten Red", 69, { Kolor: "Molten Red" }),
    ],
    collections: ["oswietlenie", "latarki-magnetyczne", "edc"],
    badges: [],
    tags: ["latarka", "edc", "magnetyczna"],
    relatedHandles: ["vanta-cob-1200", "apex-multi-12"],
    accent: "molten",
    icon: "zap",
  },
  {
    id: "p-halo-inspect",
    handle: "halo-inspect",
    title: "HALO INSPECT",
    subtitle: "Składana lampa inspekcyjna UV + COB",
    vendor: "NOCTRA",
    description:
      "Smukła lampa warsztatowa z panelem COB i trybem UV do wykrywania wycieków klimatyzacji. Składa się płasko, mieści w schowku.",
    features: [
      "Panel COB 600 lm + dioda UV 395 nm",
      "Obrót 180°, magnes i hak",
      "Wykrywanie wycieków UV (klimatyzacja, oleje)",
      "Smukła konstrukcja, ładowanie USB-C",
    ],
    specs: [
      { label: "Strumień", value: "600 lm + UV 395 nm" },
      { label: "Akumulator", value: "2600 mAh" },
      { label: "Czas pracy", value: "do 6 h" },
      { label: "Odporność", value: "IP65" },
    ],
    price: 109,
    compareAtPrice: 139,
    currencyCode: CUR,
    rating: 4.6,
    reviewCount: 318,
    images: [],
    options: [{ name: "Wariant", values: ["COB + UV", "COB"] }],
    variants: [
      variant("v-halo-uv", "COB + UV", 109, { Wariant: "COB + UV" }, 139),
      variant("v-halo-cob", "COB", 89, { Wariant: "COB" }, 119),
    ],
    collections: ["oswietlenie", "lampy-inspekcyjne", "panele-led"],
    badges: [],
    tags: ["lampa", "inspekcja", "uv"],
    relatedHandles: ["vanta-cob-1200", "probe-5-5"],
    accent: "molten",
    icon: "lightbulb",
  },
  {
    id: "p-strobe-guard",
    handle: "strobe-guard",
    title: "STROBE GUARD",
    subtitle: "Magnetyczna lampa awaryjna",
    vendor: "NOCTRA",
    description:
      "Mocna lampa ostrzegawcza na magnes — bursztynowe LED, 9 trybów błysku. Bezpieczeństwo na poboczu w sekundę.",
    features: [
      "Bursztynowe LED widoczne z 1 km",
      "9 trybów błysku, mocny magnes",
      "Wodoodporność IP66",
      "Ładowanie USB-C + powerbank awaryjny",
    ],
    specs: [
      { label: "Widoczność", value: "do 1000 m" },
      { label: "Tryby", value: "9 sekwencji" },
      { label: "Czas pracy", value: "do 20 h (błysk)" },
      { label: "Odporność", value: "IP66" },
    ],
    price: 99,
    currencyCode: CUR,
    rating: 4.8,
    reviewCount: 156,
    images: [],
    options: [{ name: "Zestaw", values: ["1 szt.", "2 szt."] }],
    variants: [
      variant("v-strobe-1", "1 szt.", 99, { Zestaw: "1 szt." }),
      variant("v-strobe-2", "2 szt.", 169, { Zestaw: "2 szt." }),
    ],
    collections: ["oswietlenie", "lampy-awaryjne"],
    badges: ["new"],
    tags: ["lampa", "awaryjna", "bezpieczenstwo"],
    relatedHandles: ["guardian-hammer", "vanta-cob-1200"],
    accent: "molten",
    icon: "triangle-alert",
  },
  {
    id: "p-probe-dual",
    handle: "probe-dual",
    title: "PROBE DUAL",
    subtitle: "Endoskop dwukamerowy 7 mm",
    vendor: "NOCTRA",
    description:
      "Dwie kamery — przednia i boczna — w jednej sondzie 7 mm. Przełączaj widok jednym dotknięciem i nie przegap żadnego detalu.",
    features: [
      "Kamera przednia + boczna, przełączanie 1 dotykiem",
      "Sonda 7 mm, 8 diod LED",
      "Kabel półsztywny 5 m",
      "USB-C, 1080p, IP67",
    ],
    specs: [
      { label: "Kamery", value: "2 × (przód + bok)" },
      { label: "Średnica", value: "7 mm" },
      { label: "Rozdzielczość", value: "1080p" },
      { label: "Kabel", value: "5 m półsztywny" },
      { label: "Odporność", value: "IP67" },
    ],
    price: 169,
    compareAtPrice: 219,
    currencyCode: CUR,
    rating: 4.7,
    reviewCount: 204,
    images: [],
    options: [{ name: "Długość", values: ["5 m", "10 m"] }],
    variants: [
      variant("v-probedual-5", "5 m", 169, { "Długość": "5 m" }, 219),
      variant("v-probedual-10", "10 m", 209, { "Długość": "10 m" }, 259),
    ],
    collections: ["inspekcja", "endoskopy-usb-c", "kamery-inspekcyjne"],
    badges: [],
    tags: ["endoskop", "kamera", "inspekcja"],
    relatedHandles: ["probe-5-5", "therma-scan"],
    accent: "volt",
    icon: "scan-eye",
  },
  {
    id: "p-therma-scan",
    handle: "therma-scan",
    title: "THERMA SCAN",
    subtitle: "Kamera termowizyjna USB-C",
    vendor: "NOCTRA",
    description:
      "Termowizja w kieszeni. Znajdź przegrzane bezpieczniki, wycieki cieplne i zatarte łożyska — podłącz do telefonu i czytaj temperaturę na żywo.",
    features: [
      "Matryca termowizyjna 256×192",
      "Zakres -20°C do 550°C",
      "Nakładka obrazu wizyjnego (fusion)",
      "USB-C, kompaktowa obudowa",
    ],
    specs: [
      { label: "Rozdzielczość", value: "256 × 192 px" },
      { label: "Zakres temperatur", value: "-20°C — 550°C" },
      { label: "Odświeżanie", value: "25 Hz" },
      { label: "Złącze", value: "USB-C" },
    ],
    price: 599,
    compareAtPrice: 749,
    currencyCode: CUR,
    rating: 4.9,
    reviewCount: 87,
    images: [],
    options: [{ name: "Edycja", values: ["Standard", "Limited Carbon"] }],
    variants: [
      variant("v-therma-std", "Standard", 599, { Edycja: "Standard" }, 749),
      variant("v-therma-carbon", "Limited Carbon", 699, { Edycja: "Limited Carbon" }, 899),
    ],
    collections: ["inspekcja", "termowizja", "mierniki"],
    badges: ["new", "limited"],
    tags: ["termowizja", "diagnostyka", "inspekcja"],
    relatedHandles: ["probe-5-5", "probe-dual"],
    accent: "volt",
    icon: "thermometer",
  },
  {
    id: "p-apex-multi-12",
    handle: "apex-multi-12",
    title: "APEX MULTI-12",
    subtitle: "Multitool 12-w-1",
    vendor: "NOCTRA",
    description:
      "Dwanaście narzędzi ze stali nierdzewnej w jednej obudowie kieszonkowej. Szczypce, ostrza, bity i otwieracz — zawsze pod ręką.",
    features: [
      "12 funkcji: szczypce, nóż, piła, bity, otwieracz",
      "Stal nierdzewna 3Cr13, blokada ostrzy",
      "Etui z nylonu + klips na pasek",
      "Waga 210 g",
    ],
    specs: [
      { label: "Funkcje", value: "12-w-1" },
      { label: "Materiał", value: "Stal 3Cr13" },
      { label: "Waga", value: "210 g" },
      { label: "Etui", value: "Nylon + klips" },
    ],
    price: 129,
    currencyCode: CUR,
    rating: 4.6,
    reviewCount: 263,
    images: [],
    options: [{ name: "Wykończenie", values: ["Black Oxide", "Satin"] }],
    variants: [
      variant("v-apex-black", "Black Oxide", 129, { "Wykończenie": "Black Oxide" }),
      variant("v-apex-satin", "Satin", 129, { "Wykończenie": "Satin" }),
    ],
    collections: ["narzedzia", "edc", "multitoole"],
    badges: [],
    tags: ["multitool", "edc", "narzedzia"],
    relatedHandles: ["guardian-hammer", "puck-mini"],
    accent: "molten",
    icon: "wrench",
  },
  {
    id: "p-guardian-hammer",
    handle: "guardian-hammer",
    title: "GUARDIAN HAMMER",
    subtitle: "Młotek bezpieczeństwa 3-w-1",
    vendor: "NOCTRA",
    description:
      "Zbijak do szyb, nóż do pasów i latarka w jednym. Mocowanie magnetyczne w zasięgu ręki — bo liczy się każda sekunda.",
    features: [
      "Grot ze stali hartowanej do zbijania szyb",
      "Ukryte ostrze do cięcia pasów",
      "Wbudowana latarka LED + magnetyczny uchwyt",
      "Pewny chwyt w mokrej dłoni",
    ],
    specs: [
      { label: "Funkcje", value: "Zbijak + nóż + LED" },
      { label: "Materiał", value: "Stal + ABS" },
      { label: "Mocowanie", value: "Magnetyczny uchwyt" },
    ],
    price: 79,
    compareAtPrice: 99,
    currencyCode: CUR,
    rating: 4.9,
    reviewCount: 512,
    images: [],
    options: [{ name: "Zestaw", values: ["1 szt.", "2 szt."] }],
    variants: [
      variant("v-guardian-1", "1 szt.", 79, { Zestaw: "1 szt." }, 99),
      variant("v-guardian-2", "2 szt.", 139, { Zestaw: "2 szt." }, 179),
    ],
    collections: ["narzedzia", "mlotki-bezpieczenstwa", "bestsellery"],
    badges: ["bestseller"],
    tags: ["bezpieczenstwo", "mlotek", "edc"],
    relatedHandles: ["strobe-guard", "apex-multi-12"],
    accent: "molten",
    icon: "shield",
  },
  {
    id: "p-torq-tray",
    handle: "torq-tray",
    title: "TORQ TRAY",
    subtitle: "Magnetyczna taca na śruby",
    vendor: "NOCTRA",
    description:
      "Koniec z gubieniem śrub. Mocne magnesy trzymają drobne części, a gumowana podstawa nie rysuje lakieru.",
    features: [
      "Silne magnesy w całej podstawie",
      "Gumowana krawędź — zero rys",
      "Średnica 150 mm, stal nierdzewna",
    ],
    specs: [
      { label: "Średnica", value: "150 mm" },
      { label: "Materiał", value: "Stal nierdzewna" },
      { label: "Magnes", value: "Pełna podstawa" },
    ],
    price: 39,
    currencyCode: CUR,
    rating: 4.5,
    reviewCount: 198,
    images: [],
    options: [{ name: "Rozmiar", values: ["150 mm", "190 mm"] }],
    variants: [
      variant("v-torq-150", "150 mm", 39, { Rozmiar: "150 mm" }),
      variant("v-torq-190", "190 mm", 49, { Rozmiar: "190 mm" }),
    ],
    collections: ["narzedzia", "tace-magnetyczne", "klucze"],
    badges: [],
    tags: ["taca", "magnetyczna", "warsztat"],
    relatedHandles: ["apex-multi-12", "vanta-cob-1200"],
    accent: "molten",
    icon: "circle-dot",
  },
  {
    id: "p-cargo-grid",
    handle: "cargo-grid",
    title: "CARGO GRID",
    subtitle: "Modułowy organizer bagażnika",
    vendor: "NOCTRA",
    description:
      "Składany organizer z regulowanymi przegrodami i systemem mocowania na rzepy. Trzyma zakupy i narzędzia na miejscu, składa się płasko.",
    features: [
      "Regulowane przegrody na rzepy",
      "Wzmocnione dno i uchwyty",
      "Składa się płasko, gdy niepotrzebny",
      "Wodoodporna tkanina 600D",
    ],
    specs: [
      { label: "Wymiary", value: "58 × 38 × 25 cm" },
      { label: "Materiał", value: "Tkanina 600D" },
      { label: "Przegrody", value: "Regulowane" },
    ],
    price: 119,
    compareAtPrice: 149,
    currencyCode: CUR,
    rating: 4.7,
    reviewCount: 341,
    images: [],
    options: [{ name: "Rozmiar", values: ["M", "L"] }],
    variants: [
      variant("v-cargo-m", "M", 119, { Rozmiar: "M" }, 149),
      variant("v-cargo-l", "L", 139, { Rozmiar: "L" }, 179),
    ],
    collections: ["organizacja", "organizery-bagaznika", "bestsellery"],
    badges: ["bestseller"],
    tags: ["organizer", "bagaznik"],
    relatedHandles: ["deck-mat", "torq-tray"],
    accent: "molten",
    icon: "box",
  },
  {
    id: "p-deck-mat",
    handle: "deck-mat",
    title: "DECK MAT",
    subtitle: "Antypoślizgowa mata bagażnika",
    vendor: "NOCTRA",
    description:
      "Gruba mata, która trzyma ładunek w miejscu i chroni bagażnik. Tnij na wymiar, myj wodą.",
    features: [
      "Antypoślizgowa guma o wysokiej przyczepności",
      "Przycinana na wymiar nożyczkami",
      "Łatwe czyszczenie wodą",
    ],
    specs: [
      { label: "Wymiary", value: "120 × 100 cm" },
      { label: "Grubość", value: "5 mm" },
      { label: "Materiał", value: "Guma EVA" },
    ],
    price: 89,
    currencyCode: CUR,
    rating: 4.4,
    reviewCount: 129,
    images: [],
    options: [{ name: "Kolor", values: ["Czarny", "Grafit"] }],
    variants: [
      variant("v-deck-black", "Czarny", 89, { Kolor: "Czarny" }),
      variant("v-deck-graphite", "Grafit", 89, { Kolor: "Grafit" }),
    ],
    collections: ["organizacja", "maty", "uchwyty"],
    badges: [],
    tags: ["mata", "bagaznik"],
    relatedHandles: ["cargo-grid"],
    accent: "molten",
    icon: "layout-grid",
  },
];

export const collections: Collection[] = [
  { handle: "oswietlenie", title: "Oświetlenie", description: "Lampy warsztatowe, latarki magnetyczne i oświetlenie inspekcyjne." },
  { handle: "lampy-cob", title: "Lampy COB", description: "Mocne panele COB z mocowaniem magnetycznym." },
  { handle: "latarki-magnetyczne", title: "Latarki magnetyczne", description: "Trzymają się każdej stalowej powierzchni." },
  { handle: "lampy-inspekcyjne", title: "Lampy inspekcyjne", description: "Smukłe lampy do pracy w ciasnych miejscach." },
  { handle: "panele-led", title: "Panele LED" },
  { handle: "lampy-awaryjne", title: "Lampy awaryjne", description: "Widoczność i bezpieczeństwo na poboczu." },
  { handle: "oswietlenie-bagaznika", title: "Oświetlenie bagażnika" },
  { handle: "akcesoria-oswietlenie", title: "Akcesoria oświetleniowe" },
  { handle: "inspekcja", title: "Inspekcja", description: "Endoskopy, kamery i diagnostyka dla kierowców." },
  { handle: "endoskopy-usb-c", title: "Endoskopy USB-C", description: "Zajrzyj w każdy zakamarek silnika." },
  { handle: "kamery-inspekcyjne", title: "Kamery inspekcyjne" },
  { handle: "sondy", title: "Sondy i kable" },
  { handle: "mierniki", title: "Mierniki i testery" },
  { handle: "termowizja", title: "Kamery termowizyjne", description: "Zobacz to, czego nie widać." },
  { handle: "narzedzia", title: "Narzędzia & EDC", description: "Multitoole, młotki bezpieczeństwa i sprzęt warsztatowy." },
  { handle: "edc", title: "EDC kierowcy" },
  { handle: "multitoole", title: "Multitoole" },
  { handle: "mlotki-bezpieczenstwa", title: "Młotki bezpieczeństwa" },
  { handle: "klucze", title: "Klucze i nasadki" },
  { handle: "tace-magnetyczne", title: "Tace magnetyczne" },
  { handle: "organizacja", title: "Organizacja", description: "Trzymaj porządek w bagażniku i garażu." },
  { handle: "organizery-bagaznika", title: "Organizery bagażnika" },
  { handle: "maty", title: "Maty i wykładziny" },
  { handle: "uchwyty", title: "Uchwyty i mocowania" },
  { handle: "bestsellery", title: "Bestsellery", description: "Najczęściej wybierane przez kierowców NOCTRA." },
  { handle: "nowosci", title: "Nowości", description: "Świeżo z linii produkcyjnej." },
];
